BabyPedia/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BabyPedia.Controllers
{
    public class ServicesController : Controller
    {
        public IActionResult OnlineConsultation()
        {
            return View();
        }

        public IActionResult Vaccination()
        {
            return View();
        }
        //
        // public IActionResult Appointment()
        // {
        //     return View();
        // }

        public IActionResult RecordTracking()
        {
            return View();
        }
    }
}

BabyPedia/Controllers/WelcomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BabyPedia.Controllers
{
    public class WelcomeController : Controller
    {
        public IActionResult ParentWelcome()
        {
            return View();
        }
        /*
         * 
access_token$sandbox$j3cyrbgqf4shn93p$639d620307359ca74bbc7e9f56dc8179
         */

        public IActionResult PediaWelcome()
        {
            return View();
        }
    }
}

BabyPedia/Views/Welcome/ParentWelcome.cshtml
@{
    ViewData["Title"] = "ParentWelcome";
}
<h1>@ViewData["Title"]</h1>

@* <input type="button" onclick="location.href='@Url.Action("OnlineConsultation", "Services")'" value=" Online Appointment" /> *@
@* <input type="button" onclick="location.href='@Url.Action("PatientRecord", "Services")'" value=" Patient Record" /> *@
@* <input type="button" onclick="location.href='@Url.Action("Vaccination", "Services")'" value=" Vaccine Information" /> *@
@* <input type="button" onclick="location.href='@Url.Action("PartneredPedia", "Services")'" value=" Partnered Pediatricians" /> *@


<p>Welcome page of the parent. </p>

BabyPedia/Views/Welcome/PediaWelcome.cshtml
@{
    ViewData["Title"] = "PediaWelcome";
}
<h1>@ViewData["Title"]</h1>
@* <input type="button" onclick="location.href='@Url.Action("OnlineConsultation", "Services")'" value=" Online Appointment" /> *@
@* <input type="button" onclick="location.href='@Url.Action("PatientRecord", "Services")'" value=" Patient Record" /> *@
@* <input type="button" onclick="location.href='@Url.Action("Vaccination", "Services")'" value=" Vaccine Information" /> *@
@* <input type="button" onclick="location.href='@Url.Action("SubPayment", "Services")'" value=" Subscription Payment" /> *@
@* <p>This is the welcome page of the pedia. </p> *@